// Generated by gencpp from file rasp_imu_hat_6dof/GetYawDataRequest.msg
// DO NOT EDIT!


#ifndef RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATAREQUEST_H
#define RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rasp_imu_hat_6dof
{
template <class ContainerAllocator>
struct GetYawDataRequest_
{
  typedef GetYawDataRequest_<ContainerAllocator> Type;

  GetYawDataRequest_()
    {
    }
  GetYawDataRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetYawDataRequest_

typedef ::rasp_imu_hat_6dof::GetYawDataRequest_<std::allocator<void> > GetYawDataRequest;

typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataRequest > GetYawDataRequestPtr;
typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataRequest const> GetYawDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rasp_imu_hat_6dof

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rasp_imu_hat_6dof/GetYawDataRequest";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetYawDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rasp_imu_hat_6dof::GetYawDataRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATAREQUEST_H
