// Generated by gencpp from file rasp_imu_hat_6dof/GetYawDataResponse.msg
// DO NOT EDIT!


#ifndef RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATARESPONSE_H
#define RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rasp_imu_hat_6dof
{
template <class ContainerAllocator>
struct GetYawDataResponse_
{
  typedef GetYawDataResponse_<ContainerAllocator> Type;

  GetYawDataResponse_()
    : yaw(0.0)  {
    }
  GetYawDataResponse_(const ContainerAllocator& _alloc)
    : yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetYawDataResponse_

typedef ::rasp_imu_hat_6dof::GetYawDataResponse_<std::allocator<void> > GetYawDataResponse;

typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataResponse > GetYawDataResponsePtr;
typedef boost::shared_ptr< ::rasp_imu_hat_6dof::GetYawDataResponse const> GetYawDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator1> & lhs, const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator1> & lhs, const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rasp_imu_hat_6dof

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2160bf7632f25ad6dc7c5aab561198d4";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2160bf7632f25ad6ULL;
  static const uint64_t static_value2 = 0xdc7c5aab561198d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rasp_imu_hat_6dof/GetYawDataResponse";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"\n"
;
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetYawDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rasp_imu_hat_6dof::GetYawDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATARESPONSE_H
