// Generated by gencpp from file rasp_imu_hat_6dof/GetYawData.msg
// DO NOT EDIT!


#ifndef RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATA_H
#define RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATA_H

#include <ros/service_traits.h>


#include <rasp_imu_hat_6dof/GetYawDataRequest.h>
#include <rasp_imu_hat_6dof/GetYawDataResponse.h>


namespace rasp_imu_hat_6dof
{

struct GetYawData
{

typedef GetYawDataRequest Request;
typedef GetYawDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetYawData
} // namespace rasp_imu_hat_6dof


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rasp_imu_hat_6dof::GetYawData > {
  static const char* value()
  {
    return "2160bf7632f25ad6dc7c5aab561198d4";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawData&) { return value(); }
};

template<>
struct DataType< ::rasp_imu_hat_6dof::GetYawData > {
  static const char* value()
  {
    return "rasp_imu_hat_6dof/GetYawData";
  }

  static const char* value(const ::rasp_imu_hat_6dof::GetYawData&) { return value(); }
};


// service_traits::MD5Sum< ::rasp_imu_hat_6dof::GetYawDataRequest> should match
// service_traits::MD5Sum< ::rasp_imu_hat_6dof::GetYawData >
template<>
struct MD5Sum< ::rasp_imu_hat_6dof::GetYawDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rasp_imu_hat_6dof::GetYawData >::value();
  }
  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasp_imu_hat_6dof::GetYawDataRequest> should match
// service_traits::DataType< ::rasp_imu_hat_6dof::GetYawData >
template<>
struct DataType< ::rasp_imu_hat_6dof::GetYawDataRequest>
{
  static const char* value()
  {
    return DataType< ::rasp_imu_hat_6dof::GetYawData >::value();
  }
  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rasp_imu_hat_6dof::GetYawDataResponse> should match
// service_traits::MD5Sum< ::rasp_imu_hat_6dof::GetYawData >
template<>
struct MD5Sum< ::rasp_imu_hat_6dof::GetYawDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rasp_imu_hat_6dof::GetYawData >::value();
  }
  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasp_imu_hat_6dof::GetYawDataResponse> should match
// service_traits::DataType< ::rasp_imu_hat_6dof::GetYawData >
template<>
struct DataType< ::rasp_imu_hat_6dof::GetYawDataResponse>
{
  static const char* value()
  {
    return DataType< ::rasp_imu_hat_6dof::GetYawData >::value();
  }
  static const char* value(const ::rasp_imu_hat_6dof::GetYawDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASP_IMU_HAT_6DOF_MESSAGE_GETYAWDATA_H
